config/routes.rb
Rails.application.routes.draw do
  devise_for :workers, controllers: {
    sessions: 'workers/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :events do
  end


  root 'application#index'

  get "workers" => "workers#index", as: "workers"

  get "workers/:worker_id" => "workers#show", as: "worker_show"


  post "workers/:id/work_times" => "work_times#create", as: "create_work_time"

  post "workers/:worker_id/work_times/:work_time_id" => "work_times#end_shift", as: "end_work_time"

  patch "work_times/:id" => "work_times#update"

  get "work_times/:id" => "work_times#show"

  post "work_times/delete/:id" => "work_times#delete"

end

app/models/event.rb
class Event < ApplicationRecord
  has_many :work_times
  has_many :work_types, through: :work_times
  has_many :workers, through: :work_times

  def self.upcoming_events
    Event.where("date >= ?", Time.zone.now.beginning_of_day).order(date: :asc, name: :asc)
  end

  def self.current_events
    Event.where("start_time <= ?", Time.zone.now.beginning_of_day).where("end_time >= ?", Time.zone.now.beginning_of_day).order(date: :asc, name: :asc)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def show
    @event = Event.includes(:workers).where(id: params[:id]).first
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event
    else
      @errors = @event
      render new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    event = Event.find(params[:id])
    event.update(event_params)
    redirect_to event
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy
    redirect_to "events"
  end

  private

  def event_params
    params.require(:event).permit(:name, :date, :start_time, :end_time)
  end

end

app/views/events/_form.html.erb
  <%= f.label :event_name, "Event Name" %>
  <%= f.text_field :name, placeholder: "Event Name" %><br<>
  <%= f.label :description %>
  <%= f.text_area :description %><br />
  <%= f.label :date, "Date" %>
  <%= f.date_field :date, placeholder: (Time.now + 1.days).strftime("%Y-%m-%d") %>
  <%# f.date_select :date, order: [:month, :day, :year], use_short_month: true, start_year: Time.now.year, default: Time.now + 1.days %>
  <%= f.label :start_time, "Start Time" %>
  <%= f.time_field :start_time %>
  <!-- <input type="time" name="event[:start_time]" /> -->
  <%# f.time_select :start_time, default: Time.zone.now.beginning_of_day + 9.hours, minute_step: 15 %>
  <%= f.label :end_time, "End Time" %>
  <%= f.time_field :end_time %>

app/views/events/edit.html.erb
<%= form_for @event do |f| %>
  <%= render partial: "form", locals: {f: f} %>
  <%= f.submit "Edit Event" %>
<% end %>

app/views/events/index.html.erb
<h3>Events</h3>
<% @events.each do |event| %>
  <h4><b><%= link_to event.name, event %></b> <%= event.date.strftime("%B %d, %Y") %></h4>
  <%= link_to :edit, edit_event_path(event) %>
  <%= button_to :delete, event_path(event), action: :delete, method: :delete, data: {confirm: "Are you sure you want to delete #{event.name}?"} %>
<% end %>

app/views/events/new.html.erb
<%= form_for @event do |f| %>
  <%= render partial: "form", locals: {f: f} %>
  <%= f.submit  %>
<% end %>

app/views/events/show.html.erb
<h3><%= @event.name %></h3>
<p>Date: <%= @event.date.strftime("%B %d, %Y") %></p>
<p>Start Time: <%= @event.start_time.strftime("%I:%M, %p") %></p>
<p>End Time: <%= @event.end_time.strftime("%I:%M, %p") %></p>
<p><%= @event.description %></p>

<% if @event.workers %>
  <ul>
    <% @event.workers.each do |worker| %>
    <li>
      <%= "#{worker.first_name} #{worker.last_name}" %>
    </li>
    <% end %>
  </ul>
<% end %>