config/routes.rb
Rails.application.routes.draw do
  devise_for :workers, controllers: {
    sessions: 'workers/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :events do
  end


  root 'application#index'

  get "workers" => "workers#index", as: "workers"

  get "workers/:worker_id" => "workers#show", as: "worker_show"


  post "workers/:id/work_times" => "work_times#create", as: "create_work_time"

  post "workers/:worker_id/work_times/:work_time_id" => "work_times#end_shift", as: "end_work_time"

  patch "work_times/:id" => "work_times#update"

  get "work_times/:id" => "work_times#show"

  post "work_times/delete/:id" => "work_times#delete"

end

app/models/worker.rb
class Worker < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :work_times
  has_many :events, through: :work_times
  # has_many :availability_schedules
  has_many :worker_skills
  has_many :skills, through: :worker_skills
  belongs_to :user_role

  def unclosed_shift

    if self.work_times.last && !self.work_times.last.work_end
      return true
    else
      return false
    end
  end

end

app/controllers/workers/confirmations_controller.rb
class Workers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/workers/omniauth_callbacks_controller.rb
class Workers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/workers/passwords_controller.rb
class Workers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/workers/registrations_controller.rb
class Workers::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/workers/sessions_controller.rb
class Workers::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    @workers = Worker.all
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/workers/unlocks_controller.rb
class Workers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController

  def index
    @admins = UserRole.find_by(role: "Admin").workers
    @volunteers = UserRole.find_by(role: "Volunteer").workers
  end

  def show
    if !current_worker
      redirect_to new_worker_session_path
    end


    if current_worker && current_worker.work_times && current_worker.work_times.last && current_worker.work_times.last.work_end == nil
      @work_time = current_worker.work_times.last
      @unclosed_shift = current_worker.work_times.last
    else
      @work_time = WorkTime.new
    end

    @worker = Worker.find(params[:worker_id])
  end

  def new
    @worker = Worker.new
  end

end

app/views/workers/index.html.erb
<h3>Administrators</h3>
  <%if @admins%>
    <ul>
      <%@admins.each do |admin|%>
        <li>
          <%= link_to("#{admin.first_name} #{admin.last_name}", worker_show_path(worker_id: admin.id))%>
        </li>
      <%end%>
    </ul>
  <%end%>

<h3>Volunteers</h3>
  <%if @volunteers%>
    <ul>
      <%@volunteers.each do |volunteer|%>
        <li>
          <%= link_to("#{volunteer.first_name} #{volunteer.last_name}", worker_show_path(worker_id: volunteer.id))%>
        </li>
      <%end%>
    </ul>
  <%end%>

app/views/workers/show.html.erb
<% if !current_worker %>
  Please log in.
<% elsif current_worker.id === @worker_id %>
  <h1><%= "Welcome, #{current_worker.first_name}!" %></h1>

  <p>Log your hours:</p>

  <% if current_worker.unclosed_shift %>
    <div class="clock-in-out">
      <p>There is an unclosed shift.  Please clock out.</p>
      <%= button_to "End Shift", end_work_time_path(worker_id: current_worker.id, work_time_id: current_worker.work_times.last.id) %>
    </div>
  <% else %>
    <p>What brings you to the Recyclery today?</p>
    <%= form_for @work_time, url: create_work_time_path(worker_id: current_worker.id) do |f| %>
      <% Event.current_events.each do |e| %> <!-- change this to use a class method to only events within an hour or something of time begin -->
        <%= f.radio_button(:event_id, e.id) %>
        <%= label(:event_id, e.name) %>
      <% end %>
      <%= f.submit "Start Shift" %>
    <% end %>
  <% end %>

  <br>
  <br>

<% else %>
  <h1><%= "#{@worker.first_name} #{@worker.last_name}" %></h1>
<% end %>


<h2>Skills:</h2>

<% @worker.worker_skills.each do |worker_skill| %>
  <%= worker_skill.skill.name %>
  <% worker_skill.proficiency.times do %>
  *
  <% end %>
  <br>
<% end %>

<h2>Recent time card activity:</h2>
<p class = "errors"></p>
<table class = "timecard">
  <tr>
    <th>Event</th>
    <th>Date</th>
    <th>Start</th>
    <th>End</th>
    <th></th>
  </tr>
  <% @worker.work_times.reverse.each do |work_time| %>
    <tr id="<%= work_time.id %>">
      <td class = "work-event">
        <%= work_time.event.name %>
      </td>
      <td class = "work-date">
        <%= work_time.work_start.to_date %>
      </td>
      <td class = "work-start">
        <%= work_time.work_start.strftime("%I:%M %p") %>
      </td>
      <td class = "work-end">
        <%if work_time.work_end%>
          <%= work_time.work_end.strftime("%I:%M %p") %>
        <%end%>
      </td>
      <td>
        <button class="edit_button">edit</button>
      </td>
      <td>
        <button class="delete_button">delete</button>
      </td>
    </tr>
  <% end %>
</table>