config/routes.rb
Rails.application.routes.draw do
  devise_for :workers, controllers: {
    sessions: 'workers/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :events do
  end


  root 'application#index'

  get "workers" => "workers#index", as: "workers"

  get "workers/:worker_id" => "workers#show", as: "worker_show"


  post "workers/:id/work_times" => "work_times#create", as: "create_work_time"

  post "workers/:worker_id/work_times/:work_time_id" => "work_times#end_shift", as: "end_work_time"

  patch "work_times/:id" => "work_times#update"

  get "work_times/:id" => "work_times#show"

  post "work_times/delete/:id" => "work_times#delete"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vtracklery20</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'worktimes', 'data-turbolinks-track': 'reload' %>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet'  type='text/css'>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">

        <div class = "navbar-header">
          <%=link_to("VTracklery", root_path, {class: "navbar-brand"})%>

          <ul class="nav navbar-nav">
            <%if current_worker%>
              <li>
                <%=link_to("profile", worker_show_path(worker_id: current_worker.id))%>
              </li>
              <li>
                <%=link_to("log out", destroy_worker_session_path, {method: "delete"})%>
              </li>

            <% else %>
              <li>
                <%=link_to("sign in", new_worker_session_path)%>
              </li>
            <%end%>

            <%if current_worker && current_worker.user_role.role === "Admin"%>
              <li>
                <%=link_to("events", events_path)%>
              </li>
              <li>
                <%=link_to("workers", workers_path)%>
              </li>
            <%end%>
          </ul>

        </div>
      </div>
    </nav>
    <br>
    <div class = "page-content">
      <%= yield %>
    </div>
    <br>
    <footer>
      <p>Created in 2017 by Ben Van Sickle, Rob Dale, and Melanie Mazanec</p>
    </footer>
  </body>
</html>

app/views/layouts/index.html.erb
<h1>Welcome to the Recyclery!</h1>

<p>To track your hours working or volunteering at the Recyclery, sign up or log in.  For hours and more information, <a href="">visit our main site</a>.</p>